import type { Metadata } from "next";
import { Unbounded } from "next/font/google";
import "./globals.css";

const unBounded = Unbounded({
  variable: "--font-unbounded",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${unBounded.variable} antialiased font-light`}>
        {children}
      </body>
    </html>
  );
}
